# Generated by Django 4.2.23 on 2025-09-17 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='valor ganho R$')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Saidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='valor gasto R$')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo R$')),
                ('mes_inicio', models.DateField(verbose_name='data inicial')),
                ('mes_fim', models.DateField(verbose_name='data final')),
                ('mes_atualizacao', models.DateField(auto_now=True, verbose_name='data de atualização')),
            ],
        ),
    ]
