# Generated by Django 4.2.23 on 2025-09-27 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_entradas_owner_alter_saidas_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldo',
            name='mes_atualizacao',
        ),
        migrations.RemoveField(
            model_name='saldo',
            name='mes_fim',
        ),
        migrations.RemoveField(
            model_name='saldo',
            name='mes_inicio',
        ),
        migrations.AddField(
            model_name='saldo',
            name='data_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora do Registro'),
        ),
    ]
