# Generated by Django 4.2.23 on 2025-09-24 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saidas',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saldo',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saidas',
            name='descricao',
            field=models.CharField(choices=[('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('moradia', 'Moradia'), ('lazer', 'Lazer'), ('outros', 'Outros')], max_length=100),
        ),
    ]
