# Generated by Django 4.2.23 on 2025-09-26 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_entradas_owner_saidas_owner_saldo_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saidas',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to=settings.AUTH_USER_MODEL),
        ),
    ]
